### GEt all entries
GET http://localhost:8000/api/v1/dictionary/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/api/v1/dictionary/create-entry HTTP/1.1
Content-Type: application/json

{
    "word": "Ome",
    "pronunciation": [
        { 
            "audio": "http://example.com", 
            "sourceUrl": "http://example.com" 
        }
    ],
    "meanings": [
        {
            "definitions": [
                "ome"
            ],
            "example": "xinechmaka ome"
        }
    ]
}

###
GET http://localhost:8000/api/v1/dictionary/single-entry?_id=67601331c91fbe9bf31f75ee HTTP/1.1
Content-Type: application/json


###
DELETE http://localhost:8000/api/v1/dictionary/delete-entry?_id=676011cac91fbe9bf31f75e4 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/api/v1/dictionary/update-entry?_id=676012c8c91fbe9bf31f75e9 HTTP/1.1
Content-Type: application/json

{
    "word": "Ome",
    "pronunciation": [
        { 
            "audio": "http://exampledos.com", 
            "sourceUrl": "http://exampledos.com" 
        }
    ],
    "meanings": [
        {
            "definitions": [
                "ome"
            ],
            "example": "xinechmaka ome"
        }
    ]
}